name: build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]
        include:
          - os: ubuntu-latest
            dist_name: bandcamp-auto-uploader
            release_name: bandcamp-auto-uploader-linux
          - os: macos-latest
            dist_name: bandcamp-auto-uploader
            release_name: bandcamp-auto-uploader-mac
          - os: windows-latest
            dist_name: bandcamp-auto-uploader.exe
            release_name: bandcamp-auto_uploader-win.exe
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt pyinstaller
      - name: Build binary with PyInstaller
        run: pyinstaller --clean -y bandcamp_auto_uploader.spec
      - name: Rename executable
        run: mv dist/${{matrix.dist_name}} ${{matrix.release_name}}
      - name: Upload release files
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: ${{matrix.release_name}}
          tag: ${{github.ref}}
          overwrite: true
