name: build

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
            pypi_token: ${{ secrets.PYPI_TOKEN }}
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]
        include:
          - os: ubuntu-latest
            dist_name: bandcamp-auto-uploader
            release_name: bandcamp-auto-uploader-linux
          - os: macos-latest
            dist_name: bandcamp-auto-uploader
            release_name: bandcamp-auto-uploader-mac
          - os: windows-latest
            dist_name: bandcamp-auto-uploader.exe
            release_name: bandcamp-auto-uploader-win.exe
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: poetry install --with build
      - name: Build binary with PyInstaller
        run: poetry run pyinstaller --clean -y bandcamp_auto_uploader.spec
      - name: Rename executable
        run: mv dist/${{matrix.dist_name}} ${{matrix.release_name}}
      - name: Upload release files
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: ${{matrix.release_name}}
          tag: ${{github.ref}}
          overwrite: true
